version: '3.8'

services:
  frontend:
    build:
      context: ./portfolio
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    env_file:
      - ./portfolio/.env
    networks:
      - react-net

  test:
    build:
      context: ./portfolio
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=test
    command: ["npm", "run", "test:ci"]
    networks:
      - react-net

networks:
  react-net:
    driver: bridge
