version: "3.8"

services:
  frontend:
    build:
      context: ./portfolio
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    env_file:
      - ./portfolio/.env
    networks:
      - react-net
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  react-net:
    driver: overlay